---
layout: default
title: 2. Controller 테스트 시, ControllerAdvice 미적용 문제에 대한 에러 처리 
parent: 📌 XAI를 활용한 취약점 분석 웹 어플리케이션
nav_order: 2
---

updated at : 2023-08-26

## Description

Controller 테스트 시, ControllerAdvice 를 거치지 않고 바로 Exception 이 반환되는 문제점이 발견되었어요.
> ControllerAdvice 을 직접 Mocking 해주었는데도 말이죠.


## Solution-1

아래는 Controller 에서 어떤 객체를 반환하냐에 따른 ControllerAdvice 캐치 유무를 설명합니다.

> [@Async](https://www.baeldung.com/spring-async) shouldn't be used on controller methods as you would have one thread per request anyway. More details: [is using @Async and CompletableFuture in controller can increase performance of our api?](https://stackoverflow.com/questions/65120202/is-using-async-and-completablefuture-in-controller-can-increase-performance-of)
>
> If a service method like cachingService.storeFeedback takes long time to be completed and you want immediate response from endpoint then it could be annotated @Async in the service layer so cachingService.storeFeedback could be executed in the background.
>
> For controller method below, neither @ExceptionHandler nor [previous answer](https://stackoverflow.com/a/45060491/5962766) would help to return HTTP error response if exception would occur in the void @Async service method:
>
>
> ```java
> @RequestMapping(path = "", method = RequestMethod.PUT)
> public ResponseEntity<String> store(@Valid @RequestBody FeedbackRequest request, String clientSource) {
>     cachingService.storeFeedback(request, ClientSource.from(clientSource));
>     return new ResponseEntity<>(OK);
> }
> ```
>
> If controller would return Future from @Async service then @ExceptionHandler should be sufficient to handle endpoint errors:
>
> ```java
> @RequestMapping(path = "", method = RequestMethod.PUT)
> public CompletableFuture<String> store(@Valid @RequestBody FeedbackRequest request, String clientSource) {
>     return cachingService.storeFeedback(request, ClientSource.from(clientSource));
> }
> ```
>
> According to [How To Do @Async in Spring](https://www.baeldung.com/spring-async):
>
> When a method return type is a Future, exception handling is easy. Future.get() method will throw the exception.
>
> But if the return type is void, exceptions will not be propagated to the calling thread. So, we need to add extra configurations to handle exceptions.
>
> Reference: [https://stackoverflow.com/questions/44138199/spring-exceptionhandler-and-multi-threading](https://stackoverflow.com/questions/44138199/spring-exceptionhandler-and-multi-threading)

**위의 글은 CompletableFuture 든 Async 어노테이션이든 Service 단 에서 비동기로 동작하고 예외를 반환하면, ControllerAdvice 가 이를 캐치할 수 없다는 것을 말하고 있죠!**

즉, ResponseEntity 를 아래와 같이 Controller 의 반환에 넣게 되면, 이를 ControllerAdvice 가 잡지 못합니다.
```java
public ResponseEntity<String> emailCodeSend(...){
    return ...;
}
```


따라서 아래의 코드처럼 Future 객체를 반환해주어야지만 ControllerAdvice 에서 이를 캐치할 수 있습니다.
```java
public CompletableFuture<ResponseEntity<String>> emailCodeSend(...){
    return ...;
}
```

하지만 위의 방법을 적용해도 api 테스트에서 잡히지 않았습니다.


## Solution-2

emailService 는 비동기로 동작합니다. 그리고 이 비동기를 기다려주는 mockMvc의 메소드인 `getAsyncResult(long milli)` 는 ControllerAdvice 를 거치지 않아요.
그래서 사전에 비동기까지 가지 않도록 예상하는 결과를 아래와 같이 미리 정의하였습니다.

`when(emailService.checkVerificationCode(any(),any())).thenThrow(new CustomException(error));`

#### Full Code

```java
@Test
@DisplayName("[BaseControllerAdvice] 잘못된 인증코드를 전송하면 BaseControllerAdvice 가 intercept 하여 ErrorResponse 를 반환해야합니다")
void emailCodeVerif() throws Exception {
    // given
    ErrorCode error = ErrorCode.BAD_CODE;
    when(emailService.checkVerificationCode(any(),any())).thenThrow(new CustomException(error));

    // when
    String result = mockMvc
            .perform(post("/user/register/code/verify")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content(objectMapper.writeValueAsString(VerifyEmailCodeRequest.builder().code("wrongCode").build()))
                    .session(session))
            .andDo(print())
            .andExpect(status().is(error.getHttpStatus().value()))
            .andReturn()
            .getResponse()
            .getContentAsString(StandardCharsets.UTF_8);

    ErrorResponse errorResponse = objectMapper.readValue(result, ErrorResponse.class);

    // then
    assertThat(errorResponse.getMessage()).isEqualTo(error.getDetail());
    assertThat(errorResponse.getCode()).isEqualTo(error.name());
}
```